# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c3da4aa3d6d3e57b2bf8c66bd69cffeb7a35e639872a7a3d89912139c26725662647fd7feba390ba3db2767711f96bb77243f55d610fb9ccc670b304bfda520a

test:
  secret_key_base: 6346554dc2c714db30316d4d27b832472d1d0f6520d6554333ac07a1aa4134acff3312426b5592d4b387eebc26c235e3b15be11f208022e68c644f7d2c95b634

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
